### PR TITLE
Wrap project with Docker

### PR DESCRIPTION
**Pull request by arnau**
Hi, I did this as an excuse to play with your project and start learning Elixir.

Thanks for the project, helped me a lot!

### CODE REVIEW

**Comment by whitfieldc** [comment]
Hey, this is great!

Could you also update the README with info on how to run this version, for the benefit of those who are less familiar with Docker?

**Comment by arnau** [comment]
@whitfieldc done.  As long as the reader has Docker installed these instructions should be enough.  Let me know what do you think.

**Comment by arnau** [comment]
A couple of things:
- I had to comment out the `exsync` as it was making Docker fail (filesystem notifications in Docker are quite tricky).
- I changed indentation on a couple of places with no other reason than me playing with Elixir :(  I can revert these changes if necessary.

**Comment by whitfieldc** [comment]
@arnau Thanks! However, I find that I'm not able to get the app to work from a clean repo simply by running `make build` and `make install`. The rethinkDB container starts, but the maru_rethink_todo container fails immediately after `make install` with status code 1.

When I  run `make build`, `make db`, and `make shell`, and then run `iex -S mix` in the container shell, elixir tells me that the dependencies aren't installed. I run `mix deps.get` and then `iex -S mix` manually in the container shell, the app starts successfully. 

After installing deps and running manually from the container shell once, `make install` works as expected. Any idea why this would be the case?

**Comment by arnau** [comment]
Ah, I think what is it.  `make shell` or `make app` (which is run by `make install`) mount the project directory inside the docker container so it _replaces_ the internal folder containing the compiled dependencies :(  I'll give it a twist to avoid this annoyance.  Sorry about that!

**Comment by arnau** [comment]
mmm, I'm having trouble getting `iex -S mix` work in a non-interactive shell.  What is the right way to run an Elixir daemon? (in foreground if possible)

**Comment by whitfieldc** [comment]
I think `mix run --no-halt` might be what you're looking for

**Comment by arnau** [comment]
Perfect!  So, now when you run `make install` it uses the compiled version created when building the Docker image (`make build`).

**Comment by whitfieldc** [comment]
@arnau Fantastic! Thanks for taking the time to do this

**Pull request merged**
